version: '3.8'

services:
  api1:
    build:
      context: ./api1
    container_name: api1
    expose:
      - "5000"
    networks:
      - app-network

  api2:
    build:
      context: ./api2
    container_name: api2
    expose:
      - "5000"
    networks:
      - app-network

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP access (to your APIs)
      - '81:81'     # NPM Admin UI (http://localhost:81)
      - '443:443'   # Optional HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
